# Generated by Django 4.0 on 2023-10-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travels', models.CharField(max_length=50)),
                ('departure_timeHours', models.CharField(max_length=2)),
                ('departure_timeMinutes', models.CharField(max_length=2)),
                ('departure_palce', models.CharField(max_length=50)),
                ('arrival_timeHours', models.CharField(max_length=2)),
                ('arrival_timeMinutes', models.CharField(max_length=2)),
                ('arrival_place', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=25)),
                ('fare', models.CharField(max_length=20)),
                ('seats_available', models.IntegerField()),
                ('ac_sleeper', models.CharField(max_length=20)),
                ('bus_num', models.CharField(default='AP04BN5444', max_length=15)),
                ('date', models.CharField(default='01/01/2021', max_length=10)),
                ('day', models.CharField(default='Friday', max_length=10)),
                ('one', models.CharField(default='#DDF4EC', max_length=10)),
                ('two', models.CharField(default='#DDF4EC', max_length=10)),
                ('three', models.CharField(default='#DDF4EC', max_length=10)),
                ('four', models.CharField(default='#DDF4EC', max_length=10)),
                ('five', models.CharField(default='#DDF4EC', max_length=10)),
                ('six', models.CharField(default='#DDF4EC', max_length=10)),
                ('seven', models.CharField(default='#DDF4EC', max_length=10)),
                ('eight', models.CharField(default='#DDF4EC', max_length=10)),
                ('nine', models.CharField(default='#DDF4EC', max_length=10)),
                ('ten', models.CharField(default='#DDF4EC', max_length=10)),
                ('elven', models.CharField(default='#DDF4EC', max_length=10)),
                ('twelve', models.CharField(default='#DDF4EC', max_length=10)),
                ('thirtn', models.CharField(default='#DDF4EC', max_length=10)),
                ('fouthn', models.CharField(default='#DDF4EC', max_length=10)),
                ('fivethn', models.CharField(default='#DDF4EC', max_length=10)),
                ('sixthn', models.CharField(default='#DDF4EC', max_length=10)),
            ],
            options={
                'db_table': 'buses_table',
            },
        ),
        migrations.CreateModel(
            name='DemoDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('demodate', models.DateTimeField()),
            ],
            options={
                'db_table': 'demodata_table',
            },
        ),
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromplace', models.CharField(max_length=100)),
                ('toplace', models.CharField(max_length=100)),
                ('distance', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'distances',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=50)),
                ('departure_timeHours', models.CharField(max_length=2)),
                ('departure_timeMinutes', models.CharField(max_length=2)),
                ('departure_palce', models.CharField(max_length=50)),
                ('arrival_timeHours', models.CharField(max_length=2)),
                ('arrival_timeMinutes', models.CharField(max_length=2)),
                ('arrival_place', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=25)),
                ('fare', models.CharField(max_length=20)),
                ('seats_available', models.IntegerField()),
                ('date', models.CharField(default='01/01/2021', max_length=10)),
                ('day', models.CharField(default='Wednesday', max_length=10)),
            ],
            options={
                'db_table': 'flights_table',
            },
        ),
        migrations.CreateModel(
            name='SeasonsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'SeasonalData',
            },
        ),
        migrations.CreateModel(
            name='TouristPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('cost', models.PositiveIntegerField()),
                ('time', models.PositiveIntegerField()),
                ('state', models.CharField(default='None', max_length=100)),
            ],
            options={
                'db_table': 'touristplaces',
            },
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('touristplces_covered', models.CharField(max_length=500)),
                ('hotel', models.CharField(max_length=150)),
                ('cost', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Tours',
            },
        ),
        migrations.CreateModel(
            name='TravelsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travels', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'TravelsData_table',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('FeMale', 'FeMale')], max_length=100)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'userdata_table',
            },
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'userlogin_table',
            },
        ),
        migrations.CreateModel(
            name='VisitingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('population', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'touristsData_table',
            },
        ),
    ]
