# Generated by Django 4.0 on 2023-10-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='sclass',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Pre.Economy', 'Pre.Economy'), ('Business', 'Business')], default='Economy', max_length=100),
        ),
    ]
