# Generated by Django 4.0 on 2023-10-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_flights_sclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('attractions', models.CharField(max_length=100)),
                ('visiting_day', models.PositiveIntegerField()),
                ('in_time', models.PositiveIntegerField()),
                ('out_time', models.PositiveIntegerField()),
                ('ticket_cost', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'itinerary',
            },
        ),
    ]
