# Generated by Django 4.0 on 2023-11-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='eight',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='elven',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='five',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='fivethn',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='four',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='fouthn',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='nine',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='one',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='seven',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='six',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='sixthn',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='ten',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='thirtn',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='three',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='twelve',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
        migrations.AddField(
            model_name='flights',
            name='two',
            field=models.CharField(default='#DDF4EC', max_length=10),
        ),
    ]
