# Generated by Django 4.0 on 2023-11-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_user_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_confirmed',
        ),
    ]
